# Generated by Django 3.0.4 on 2020-03-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('website', models.URLField(blank=True, db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(choices=[('0', 'Red'), ('1', 'Orange'), ('2', 'Yellow'), ('3', 'Green'), ('4', 'Blue'), ('5', 'Indigo'), ('6', 'Violet'), ('7', 'Black'), ('8', 'White')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('brand_name', models.CharField(max_length=25)),
                ('material', models.CharField(max_length=25)),
                ('fasten_type', models.CharField(max_length=25)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.ShoeColor')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Manufacturer')),
                ('shoe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.ShoeType')),
            ],
        ),
    ]
